
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "secret-manager-vite-gemini-api-key" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "comdottasteslikegood"
  name        = "vite-gemini-api-key"
  secret_data = "DUMMY_SECRET_DATA"
  depends_on  = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "postgresql-db" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id                  = "comdottasteslikegood"
  region                      = "us-west2"
  name                        = "vegangenius-chef-db"
  edition                     = "ENTERPRISE_PLUS"
  database_version            = "POSTGRES_15"
  availability_type           = "REGIONAL"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  data_cache_enabled          = true
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users = [{
    email = module.flask-backend.service_account_id.email
    id    = module.flask-backend.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
  depends_on = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "db-credentials-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "comdottasteslikegood"
  name        = "vegangenius-chef-db-credentials"
  secret_data = module.postgresql-db.generated_user_password
  depends_on  = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "express-frontend" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "comdottasteslikegood"
  location                      = "us-west2"
  service_name                  = "express-frontend"
  containers                    = [{"env_vars" = {"flask_backend_SERVICE_ENDPOINT" = module.flask-backend.service_uri}, "ports" = {"container_port" = 8080}, "container_image" = "gcr.io/comdottasteslikegood/express-frontend-image", "container_name" = "service-container", "env_secret_vars" = merge({"secret_manager_vite_gemini_api_key_SECRET" = module.secret-manager-vite-gemini-api-key.env_vars.SECRET}, {"VITE_GEMINI_API_KEY" = {"secret" = "secret-manager-vite-gemini-api-key", "version" = "latest"}})}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/run.invoker"])
  ingress                       = "INGRESS_TRAFFIC_ALL"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "flask-backend" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "comdottasteslikegood"
  location                      = "us-west2"
  service_name                  = "flask-backend"
  containers                    = [{"container_image" = "gcr.io/comdottasteslikegood/flask-backend-image", "container_name" = "service-container", "env_secret_vars" = merge({"db_credentials_secret_SECRET" = module.db-credentials-secret.env_vars.SECRET}, {"DATABASE_URL" = {"secret" = "db-credentials-secret", "version" = "latest"}}), "env_vars" = {"postgresql_db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.postgresql-db.instance_connection_name, "postgresql_db_CLOUD_SQL_DATABASE_HOST" = module.postgresql-db.instance_first_ip_address, "postgresql_db_CLOUD_SQL_DATABASE_NAME" = module.postgresql-db.env_vars.CLOUD_SQL_DATABASE_NAME}, "ports" = {"container_port" = 8080}, "volume_mounts" = [{"mount_path" = "/cloudsql", "name" = "cloudsql"}]}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"])
  ingress                       = "INGRESS_TRAFFIC_ALL"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat([module.postgresql-db.apphub_service_uri], [module.express-frontend.apphub_service_uri], [module.flask-backend.apphub_service_uri])
  application_id = var.apphub_application_id
}
module "project-services-comdottasteslikegood" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "comdottasteslikegood"
  disable_services_on_destroy = false
  activate_apis               = ["cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "iam.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "pubsub.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "servicenetworking.googleapis.com", "serviceusage.googleapis.com", "sqladmin.googleapis.com", "storage-api.googleapis.com"]
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "comdottasteslikegood"
  disable_services_on_destroy = false
  activate_apis               = ["apphub.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "iam.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "pubsub.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "servicenetworking.googleapis.com", "serviceusage.googleapis.com", "sqladmin.googleapis.com", "storage-api.googleapis.com"]
}
