
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "secret-manager-vite-gemini-api-key" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "comdottasteslikegood"
  name        = "vite-gemini-api-key"
  secret_data = "AIzaSyAICTU_cyMgCYgvcY35Lpfx8DQyyUT7h08"
  depends_on  = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "postgresql-db" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id                  = "comdottasteslikegood"
  region                      = "us-central1"
  name                        = "vegangenius-chef-db"
  edition                     = "ENTERPRISE_PLUS"
  database_version            = "POSTGRES_15"
  availability_type           = "REGIONAL"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  data_cache_enabled          = true
  tier                        = "db-c4a-highmem-2"
  zone                        = "us-central1-a"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users  = concat([{"email" = module.flask-backend.service_account_id.email, "id" = module.flask-backend.service_account_id.id, "type" = "CLOUD_IAM_SERVICE_ACCOUNT"}], [{"type" = "CLOUD_IAM_SERVICE_ACCOUNT", "email" = module.db-migration-job.service_account_id.email, "id" = module.db-migration-job.service_account_id.id}])
  depends_on = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "db-credentials-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "comdottasteslikegood"
  name        = "vegangenius-chef-db-credentials"
  secret_data = module.postgresql-db.generated_user_password
  depends_on  = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "express-frontend" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "comdottasteslikegood"
  location                      = "us-central1"
  service_name                  = "express-frontend"
  containers                    = [{"env_secret_vars" = merge({"secret_manager_vite_gemini_api_key_SECRET" = module.secret-manager-vite-gemini-api-key.env_vars.SECRET}, {"VITE_GEMINI_API_KEY" = {"version" = "latest", "secret" = "secret-manager-vite-gemini-api-key"}}), "env_vars" = {"FLASK_BACKEND_URL" = module.flask-backend.service_uri}, "ports" = {"container_port" = 8080, "name" = "http1"}, "resources" = {"cpu_idle" = true, "startup_cpu_boost" = false}, "container_image" = "gcr.io/comdottasteslikegood/vegangenius/express-frontend:latest", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/secretmanager.secretAccessor"], ["roles/run.invoker"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "flask-backend" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "comdottasteslikegood"
  location                      = "us-central1"
  service_name                  = "flask-backend"
  containers                    = [{"resources" = {"cpu_idle" = true, "startup_cpu_boost" = false}, "volume_mounts" = [{"mount_path" = "/cloudsql", "name" = "cloudsql"}], "container_image" = "gcr.io/comdottasteslikegood/vegangenius/flask-backend:latest", "container_name" = "service-container", "env_secret_vars" = merge({"db_credentials_secret_SECRET" = module.db-credentials-secret.env_vars.SECRET}, {"flask_secret_key_SECRET" = module.flask-secret-key.env_vars.SECRET}, {"DATABASE_URL" = {"version" = "latest", "secret" = "db-credentials-secret"}}), "env_vars" = merge({"postgresql_db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.postgresql-db.instance_connection_name, "postgresql_db_CLOUD_SQL_DATABASE_HOST" = module.postgresql-db.instance_first_ip_address, "postgresql_db_CLOUD_SQL_DATABASE_NAME" = module.postgresql-db.env_vars.CLOUD_SQL_DATABASE_NAME}, {"FRONTEND_URL" = "https://veganchef.tasteslikegood.org"}), "ports" = {"container_port" = 8080, "name" = "http1"}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_ONLY"
  volumes = [{
    name = "cloudsql"
    cloud_sql_instance = {
      instances = [module.postgresql-db.instance_connection_name]
    }
  }]
  service_scaling = {
    min_instance_count = 1
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "flask-secret-key" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "comdottasteslikegood"
  name        = "flask-secret-key"
  secret_data = "be59856244822b3a2e1ce63cc4a7559820fc4afaf08082a5401fe8f84c020737"
  depends_on  = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "express-frontend-lb-frontend" {
  source                          = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v14.2.0"
  name                            = "express-frontend-lb-frontend"
  project_id                      = "comdottasteslikegood"
  url_map_input                   = module.express-frontend-lb-backend.backend_service_info
  http_forward                    = true
  ssl                             = true
  managed_ssl_certificate_domains = ["veganchef.tasteslikegood.org"]
  depends_on                      = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "express-frontend-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name       = "express-frontend-lb-backend"
  project_id = "comdottasteslikegood"
  serverless_neg_backends = [{
    region          = module.express-frontend.location
    service_name    = module.express-frontend.service_name
    service_version = ""
    type            = "cloud-run"
  }]
  cdn_policy = {
    cache_mode                   = "CACHE_ALL_STATIC"
    client_ttl                   = 3600
    default_ttl                  = 3600
    max_ttl                      = 86400
    signed_url_cache_max_age_sec = "0"
  }
  depends_on = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "db-migration-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "comdottasteslikegood"
  name        = "db-migration-secret"
  secret_data = module.postgresql-db.generated_user_password
  depends_on  = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "db-migration-job" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "comdottasteslikegood"
  location                      = "us-central1"
  service_name                  = "db-migration-job"
  containers                    = [{"env_secret_vars" = merge({"db_migration_secret_SECRET" = module.db-migration-secret.env_vars.SECRET}, {"DB_CONNECTION_STRING" = {"secret" = "db-migration-secret", "version" = "latest"}}), "env_vars" = {"postgresql_db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.postgresql-db.instance_connection_name, "postgresql_db_CLOUD_SQL_DATABASE_HOST" = module.postgresql-db.instance_first_ip_address, "postgresql_db_CLOUD_SQL_DATABASE_NAME" = module.postgresql-db.env_vars.CLOUD_SQL_DATABASE_NAME}, "resources" = {"limits" = {"cpu" = "1", "memory" = "512Mi"}}, "volume_mounts" = [{"name" = "cloudsql", "mount_path" = "/cloudsql"}], "container_image" = "gcr.io/comdottasteslikegood/vegangenius/migration-task:latest", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  volumes = [{
    name = "cloudsql"
    cloud_sql_instance = {
      instances = [module.postgresql-db.instance_connection_name]
    }
  }]
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  timeout         = "300s"
  service_account = "vegangenius-chef@comdottasteslikegood.iam.gserviceaccount.com"
  depends_on      = [module.project-services-comdottasteslikegood, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat([module.postgresql-db.apphub_service_uri], [module.express-frontend.apphub_service_uri], [module.flask-backend.apphub_service_uri], module.express-frontend-lb-frontend.apphub_service_uri, module.express-frontend-lb-backend.apphub_service_uri, [module.db-migration-job.apphub_service_uri])
  application_id = var.apphub_application_id
}
module "project-services-comdottasteslikegood" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "comdottasteslikegood"
  disable_services_on_destroy = false
  activate_apis               = ["certificatemanager.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "iam.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "pubsub.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "servicenetworking.googleapis.com", "serviceusage.googleapis.com", "sqladmin.googleapis.com", "storage-api.googleapis.com", "vpcaccess.googleapis.com"]
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "comdottasteslikegood"
  disable_services_on_destroy = false
  activate_apis               = ["apphub.googleapis.com", "certificatemanager.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "iam.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "pubsub.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "servicenetworking.googleapis.com", "serviceusage.googleapis.com", "sqladmin.googleapis.com", "storage-api.googleapis.com", "vpcaccess.googleapis.com"]
}
