
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "express-frontend_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.express-frontend.service_uri
}
output "flask-backend_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.flask-backend.service_uri
}
output "express-frontend-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.express-frontend-lb-frontend.external_ip
}
output "express-frontend-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.express-frontend-lb-frontend.external_ipv6_address
}
output "express-frontend-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.express-frontend-lb-frontend.ip_address_internal_managed_http
}
output "express-frontend-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.express-frontend-lb-frontend.ip_address_internal_managed_https
}
output "db-migration-job_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.db-migration-job.service_uri
}
