#!/usr/bin/env python3
"""Sprint 11 HARD GATE — no committed Sprint 11 item may sit in To Do.

Sprint 11 successor of ``sprint10_hard_gate.py``: the same rules with Sprint 11
constants. ``--charter`` is the day-1 form named by RCP-124. It runs rules 1, 2
and 4 and requires the sprint to be ``active``; it skips rule 3, because on
day 1 every item is legitimately in To Do. ``--charter`` proves the board is
honest at charter time; the full gate is the close gate.

This is the gate the Sprint 11 close is judged by. It is read-only and lives in
its own file on purpose: nothing that can move an issue shares a module with the
check that reads it. Do not edit this file to make a run pass. If the gate is
wrong, change it in its own commit, with a reason, before the run that needs it.

The rule
--------
Exit 0 only when ALL of these hold:

1. **Sprint 11 exists** on the RCP scrum board and is ``active`` or ``closed``.
   Without this, "no sprint" would mean "no items" would mean "gate passes".
2. **Every committed item is a sprint member.** Otherwise the gate could be
   satisfied by emptying the sprint.
3. **No committed item that is in the sprint sits in the To Do status
   category.** Done, In Progress and In Review all pass.
4. **Every committed SI has an RCP acceptance row the BOARD ACTUALLY RENDERS**
   (KAN-260). Board 168's filter is ``project = RCP ORDER BY Rank ASC``, so a
   KAN key added to the sprint is a member that no column can show. Rule 4
   reads the board-scoped endpoint and asserts one RCP ``S11 acceptance:`` Story
   per SI. It is not a member/rendered delta: KAN execution rows are supposed
   to be members (rule 2) and cannot render. ``sprint10_hard_gate.py`` records
   why in full.

The split
---------
Sprint 11 is the readiness sprint. Articles, the launch post and the cooking
half of the tested-recipe proof stay under epic RCP-119 for Sprint 12 (Adam,
2026-10-09). ``NOT_IN_SPRINT`` names those rows; the charter and close gates
fail if one of them is in the sprint or on the board.

Droppable items
---------------
Sprint 11 pre-authorises none. An unplanned level-1 production item displaces
work from the bottom of the ordered list in specs/SPRINT_11_PLAN.md, and the
displaced items are named there the same day. That is a charter update with a
matching change to this file in its own commit, not a gate edit to pass a run.

What this gate does NOT prove
-----------------------------
Status alone is weak evidence. A Jira global rule moves a ticket
``To Do -> In Progress`` when a branch is created for it. Passing here means
the board is honest, not that the sprint is done; each acceptance row closes
on the evidence named on it.

Usage
-----
    python3 scripts/harness/sprint11_hard_gate.py            # full (close) gate
    python3 scripts/harness/sprint11_hard_gate.py --charter  # day-1 gate
    python3 scripts/harness/sprint11_hard_gate.py --issues KAN-306
    python3 scripts/harness/sprint11_hard_gate.py --json

Exit codes: 0 pass · 1 gate failed · 2 configuration or API error.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _jira_client import Jira  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "pm"))
from _atlassian_guard import AtlassianGuardError  # noqa: E402

RCP_SCRUM_BOARD = 168
SPRINT_NAME = "Sprint 11"

# Committed items that must be in the sprint and, at close, out of To Do.
# Charter: specs/SPRINT_11_PLAN.md. SI numbers are the plan's ordered list.
REQUIRED = {
    "RCP-123": "epic — Sprint 11 delivery/acceptance",
    "KAN-350": "charter — execution row; closes with RCP-124",
    "KAN-319": "S1  — footer and home page link the tag hubs",
    "KAN-349": "S2  — public recipe pages link the hubs top and bottom",
    "KAN-348": "S3  — home page newest-recipes row",
    "KAN-306": "S4  — generator save during deferred startup auth is persisted",
    "KAN-333": "S5  — saves that fail to reach the server say so",
    "KAN-335": "S6  — rate-limiter follow-up from the v0.5.8 review",
    "KAN-341": "S7  — recipe view Add to Cookbook button",
    "KAN-342": "S8  — Previous and Next links on public recipe pages",
    "KAN-343": "S9  — page-number nav in the browse header",
    "KAN-344": "S10 — Switch user through Google's account chooser",
    "KAN-334": "S11 — publish toggle shows the server's state",
    "KAN-336": "S12 — Backend review follow-ups from the publish-gate release",
    "KAN-337": "S13 — publish-audit and write-pause operations",
    "KAN-290": "S14 — recycle bin server-side",
    "KAN-320": "S15 — Recipe JSON-LD recommended fields",
    "KAN-273": "S16 — recipe pages not crawl dead-ends; rich-result warnings decided",
    "KAN-272": "S17 — home page landing ship criteria",
    "KAN-274": "S18 — tag hubs ship criteria",
    "KAN-276": "S19 — SPA-only routes noindex ship criteria",
    "KAN-347": "S20 — crawl-evidence instrument",
    "KAN-323": "S21 — gh-aw upgrade and recompile",
    "KAN-311": "S22 — Docker Hub links the site",
    "KAN-312": "S22 — YouTube About links the site",
    "KAN-313": "S22 — owned Meta profiles link the site",
    "KAN-346": "S23 — tested-recipe marker and /about authorship (code half)",
    "KAN-309": "S24 — Pinterest pin variant as a 1:1 centre crop",
    "KAN-345": "S25 — recipe feedback pre-build steps",
    "KAN-351": "S26 — readiness walk, mobile LCP medians, hub-link counts",
    # S27: added by Adam on 2026-10-09, during chartering, so the build of the
    # feedback feature has its own row instead of waiting for the next charter.
    "KAN-356": "S27 — recipe feedback Phase 1 build",
}

# Recorded, not committed: work added to the record after it was done. None yet.
RECORDED = {}

# Sprint items -> the execution rows that carry them. The charter pair is gated
# like an SI. S22 is one deliverable (every owned property links the site) with
# one execution row per property.
SI_EXECUTION = {
    "charter": ["KAN-350"],
    "S1": ["KAN-319"],
    "S2": ["KAN-349"],
    "S3": ["KAN-348"],
    "S4": ["KAN-306"],
    "S5": ["KAN-333"],
    "S6": ["KAN-335"],
    "S7": ["KAN-341"],
    "S8": ["KAN-342"],
    "S9": ["KAN-343"],
    "S10": ["KAN-344"],
    "S11": ["KAN-334"],
    "S12": ["KAN-336"],
    "S13": ["KAN-337"],
    "S14": ["KAN-290"],
    "S15": ["KAN-320"],
    "S16": ["KAN-273"],
    "S17": ["KAN-272"],
    "S18": ["KAN-274"],
    "S19": ["KAN-276"],
    "S20": ["KAN-347"],
    "S21": ["KAN-323"],
    "S22": ["KAN-311", "KAN-312", "KAN-313"],
    "S23": ["KAN-346"],
    "S24": ["KAN-309"],
    "S25": ["KAN-345"],
    "S26": ["KAN-351"],
    "S27": ["KAN-356"],
}

# Sprint items -> the RCP acceptance Story the BOARD renders for them. ``None``
# means the row was never filed — a violation, not a skip (KAN-260). S24 reuses
# RCP-117, the row filed for KAN-309 in Sprint 10 and retitled at this charter.
ACCEPTANCE = {
    "charter": "RCP-124",
    "S1": "RCP-125",
    "S2": "RCP-126",
    "S3": "RCP-127",
    "S4": "RCP-128",
    "S5": "RCP-129",
    "S6": "RCP-130",
    "S7": "RCP-131",
    "S8": "RCP-132",
    "S9": "RCP-133",
    "S10": "RCP-134",
    "S11": "RCP-135",
    "S12": "RCP-136",
    "S13": "RCP-137",
    "S14": "RCP-138",
    "S15": "RCP-139",
    "S16": "RCP-140",
    "S17": "RCP-141",
    "S18": "RCP-142",
    "S19": "RCP-143",
    "S20": "RCP-144",
    "S21": "RCP-145",
    "S22": "RCP-146",
    "S23": "RCP-147",
    "S24": "RCP-117",
    "S25": "RCP-148",
    "S26": "RCP-149",
    "S27": "RCP-150",
}

# Sprint 11 pre-authorises no drops. Dropping anything is a charter update.
DROPPABLE_SIS = set()
DROPPABLE = {}

# Rows that stay under RCP-119 for Sprint 12 (Adam, 2026-10-09). No rule here
# may require them; the charter and close gates fail if any of them is in the
# sprint or on the board, because that would pull launch work back into the
# readiness sprint without a charter update.
NOT_IN_SPRINT = {
    "KAN-277": "articles under the Q6 rubric (links half is S22)",
    "RCP-109": "acceptance row for the articles",
    "KAN-299": "launch post and 7-day readout",
    "RCP-110": "acceptance row for the launch post",
    "KAN-352": "cooking half of the tested-recipe proof (code half is S23)",
}

COMMITTED = dict(REQUIRED, **DROPPABLE)
# Everything the gate enforces: the commitment plus the recorded hotfix items.
# REQUIRED and COMMITTED stay the commitment alone.
GATED = dict(COMMITTED, **RECORDED)
TODO_CATEGORY_KEYS = {"new", "undefined"}


def is_todo(fields):
    cat = fields["status"].get("statusCategory") or {}
    if cat.get("key"):
        return cat["key"].lower() in TODO_CATEGORY_KEYS
    return (cat.get("name") or "").strip().lower() == "to do"


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--issues", nargs="+", default=None,
                      help="scoped check: only these keys must be out of To Do "
                           "(skips the sprint-membership rules)")
    mode.add_argument("--charter", action="store_true",
                      help="day-1 gate: rules 1, 2, 4 with the sprint active; "
                           "skips rule 3 (To Do)")
    p.add_argument("--json", action="store_true", help="machine-readable output")
    args = p.parse_args()

    try:
        jira = Jira()
    except (SystemExit, AtlassianGuardError) as exc:
        # SystemExit covers missing creds; AtlassianGuardError covers a
        # disallowed ATLASSIAN_URL (e.g. the -dev service site). Both are
        # configuration errors and must funnel to exit-2, per the docstring.
        print("CONFIG ERROR: %s" % exc, file=sys.stderr)
        return 2

    gate = (
        "sprint11-charter" if args.charter
        else "sprint11-scoped-status" if args.issues is not None
        else "sprint11-no-todo"
    )
    report = {"gate": gate, "checks": [], "violations": [], "passed": False}
    status_descriptions = dict(GATED)

    try:
        if args.issues:
            scope = list(args.issues)
        else:
            sprint = next((s for s in jira.sprints(RCP_SCRUM_BOARD)
                           if s["name"].strip().lower() == SPRINT_NAME.lower()), None)
            if not sprint:
                report["violations"].append(
                    "Sprint 11 does not exist on board %d — a missing sprint is a "
                    "vacuous pass, not a pass" % RCP_SCRUM_BOARD)
                return finish(report, args)
            report["sprint"] = {"id": sprint["id"], "state": sprint["state"]}
            allowed = ("active",) if args.charter else ("active", "closed")
            if sprint["state"] not in allowed:
                report["violations"].append(
                    "Sprint 11 is %r; expected %s" % (sprint["state"], " or ".join(allowed)))
            members = {i["key"] for i in jira.sprint_issues(sprint["id"])}
            report["member_count"] = len(members)
            for key, what in sorted(dict(REQUIRED, **RECORDED).items()):
                if key not in members:
                    report["violations"].append(
                        "%s is not in Sprint 11 (%s) — required items cannot be "
                        "dropped without a charter update" % (key, what))
            report["dropped"] = sorted(k for k in DROPPABLE if k not in members)

            # Rule 4 — board visibility. Read what the BOARD renders, not what the
            # sprint contains; the module docstring explains why this is not a
            # member/rendered delta.
            rendered = {i["key"] for i in
                        jira.board_sprint_issues(RCP_SCRUM_BOARD, sprint["id"])}
            report["board_rendered"] = sorted(rendered)

            # The split is enforced, not just recorded: a row that stays under
            # RCP-119 for Sprint 12 must not be in this sprint or on its board.
            for key, what in sorted(NOT_IN_SPRINT.items()):
                if key in members or key in rendered:
                    report["violations"].append(
                        "%s (%s) stays under RCP-119 for Sprint 12 but is in "
                        "Sprint 11 — remove it from sprint %s, or record a "
                        "charter update" % (key, what, sprint["id"]))
            report["acceptance"] = {}
            active_acceptance = {}
            for si in sorted(SI_EXECUTION):
                dropped = not any(k in members for k in SI_EXECUTION[si])
                row = ACCEPTANCE.get(si)
                if dropped and si in DROPPABLE_SIS:
                    if not row:
                        report["acceptance"][si] = "dropped — MISSING MAPPING"
                        report["violations"].append(
                            "%s is treated as dropped but has no acceptance-row "
                            "mapping, so the gate cannot prove the SI was removed "
                            "as a unit" % si)
                    elif row in members or row in rendered:
                        report["acceptance"][si] = "STRANDED — %s" % row
                        report["violations"].append(
                            "%s is treated as dropped because execution row(s) %s "
                            "left Sprint 11, but acceptance row %s remains in the "
                            "sprint/board — remove the SI as a unit"
                            % (si, "/".join(SI_EXECUTION[si]), row))
                    else:
                        report["acceptance"][si] = "dropped"
                    continue
                report["acceptance"][si] = row
                if not row:
                    report["violations"].append(
                        "%s has no RCP acceptance row — board %d filters "
                        "`project = RCP`, so its execution row(s) %s are sprint "
                        "members that no column renders"
                        % (si, RCP_SCRUM_BOARD, "/".join(SI_EXECUTION[si])))
                elif row not in rendered:
                    report["violations"].append(
                        "%s's acceptance row %s is not rendered by board %d for "
                        "this sprint — add it to the sprint, or the item is "
                        "invisible on the board" % (si, row, RCP_SCRUM_BOARD))
                else:
                    active_acceptance[row] = "%s — board-visible acceptance" % si

            # Acceptance rows are first-class committed sprint artifacts too;
            # rule 3 must reject one left in To Do just like its execution row.
            # Use setdefault so a row already described by GATED keeps its
            # more specific charter/timebox context.
            for k, v in active_acceptance.items():
                status_descriptions.setdefault(k, v)
            scope = ({k for k in GATED if k in members}
                     | {k for k in active_acceptance if k in members})

        if args.charter:
            scope = []  # rule 3 is the close gate; day 1 is all To Do by design
        for key in sorted(scope):
            f = jira.issue(key, fields="summary,status")["fields"]
            todo = is_todo(f)
            report["checks"].append({
                "key": key, "status": f["status"]["name"],
                "category": (f["status"].get("statusCategory") or {}).get("name"),
                "todo": todo,
            })
            if todo:
                report["violations"].append(
                    "%s is in To Do (%s) — %s"
                    % (key, f["status"]["name"],
                       status_descriptions.get(key, "scoped check")))
    except RuntimeError as exc:
        print("API ERROR: %s" % exc, file=sys.stderr)
        return 2

    return finish(report, args)


def finish(report, args):
    report["passed"] = not report["violations"]
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        for c in report["checks"]:
            print("%-9s %-14s %s" % (c["key"], c["status"], "TO DO" if c["todo"] else "ok"))
        for si, row in sorted(report.get("acceptance", {}).items()):
            print("%-9s %-14s %s" % (si, "acceptance",
                                     row if row else "MISSING — no RCP row"))
        for d in report.get("dropped", []):
            print("%-9s %-14s dropped from sprint (D6 timebox) — exempt"
                  % (d, "-"))
        if report["violations"]:
            print("\nHARD GATE FAILED — %d violation(s):" % len(report["violations"]))
            for v in report["violations"]:
                print("  - %s" % v)
        elif report["gate"] == "sprint11-scoped-status":
            print("\nSCOPED CHECK PASSED — every requested issue is out of To Do.")
        else:
            print("\nHARD GATE PASSED — every committed or recorded Sprint 11 item is %s AND has an "
                  "acceptance row the board renders." % (
                      "a member of the active sprint"
                      if report["gate"] == "sprint11-charter"
                      else "out of To Do"))
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
