#!/usr/bin/env python3
"""Sprint 9 HARD GATE — no committed Sprint 9 item may sit in To Do.

This is the gate the Sprint 9 agent-harness is judged by. It is read-only and
lives in its own file on purpose: nothing that can move an issue shares a module
with the check that reads it. Do not edit this file to make a run pass — that is
the reward-hacking failure mode the harness exists to prevent. If the gate is
wrong, change it in its own commit, with a reason, before the run that needs it.

The rule
--------
Exit 0 only when ALL of these hold:

1. **Sprint 9 exists** on the RCP scrum board and is ``active`` or ``closed``.
   Without this, "no sprint" would mean "no items" would mean "gate passes" —
   the vacuous pass the Sprint 9 charter names in R2.
2. **Every non-droppable committed item is a sprint member.** Otherwise the gate
   could be satisfied by emptying the sprint.
3. **No committed item that is in the sprint sits in the To Do status
   category.** Done, In Progress and In Review all pass — matching the sprint's
   definition of done: every item is delivered, in review, or consciously
   dropped.

Droppable items
---------------
Charter decision D6 pre-authorises dropping S5 (KAN-209), S7 (RCP-67) and S8
(KAN-176) against their half-day timeboxes. A dropped item is one *removed from
the sprint* — that is the board-visible act of dropping, and it exempts the item
from rule 3. Every other item must be present and out of To Do; dropping one
requires a charter update, not a gate edit.

What this gate does NOT prove
-----------------------------
Status alone is weak evidence. A Jira global rule still moves a ticket
``To Do -> In Progress`` when a branch is created for it, so an item can leave
To Do without any work happening. That is why each harness task carries its own
artifact check (PR state, CI rollup) and a named-evidence requirement on top of
this gate. Passing here means the board is honest, not that the sprint is done.

Usage
-----
    python3 scripts/harness/sprint9_hard_gate.py            # full gate
    python3 scripts/harness/sprint9_hard_gate.py --issues KAN-151
    python3 scripts/harness/sprint9_hard_gate.py --json

Exit codes: 0 pass · 1 gate failed · 2 configuration or API error.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _jira_client import Jira  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "pm"))
from _atlassian_guard import AtlassianGuardError  # noqa: E402

RCP_SCRUM_BOARD = 168
SPRINT_NAME = "Sprint 9"

# Committed items that must be in the sprint and out of To Do.
REQUIRED = {
    "RCP-88": "epic — Sprint 9 delivery/acceptance",
    "KAN-255": "S1a — image metadata never re-syncs after nav-away",
    "KAN-256": "S1a — generator does not reset on route entry",
    "KAN-257": "S1b — recipe-detail bounces to /kitchen; replaceUrl kills Back",
    "KAN-151": "S2  — Valkey response cache restore (ANCHOR)",
    "KAN-249": "S3  — split cloudbuild.staging.yaml out of cloudbuild.yaml",
    "KAN-250": "S3  — staging deploy moves to a GCP-side Cloud Build trigger",
    "KAN-258": "S4  — model-selection tail + v0.4.13 release cut",
    "KAN-195": "S6  — regenerated image blocked 24h by stale Cache-Control",
}

# D6 pre-authorised drops. Absent from the sprint == dropped == exempt.
DROPPABLE = {
    "KAN-209": "S5  — RESP2 pin revisit (half-day timebox)",
    "RCP-67": "S7  — route/request classification contract (half-day timebox)",
    "KAN-176": "S8  — flask-backend second guard (half-day timebox)",
}

COMMITTED = dict(REQUIRED, **DROPPABLE)
TODO_CATEGORY_KEYS = {"new", "undefined"}


def is_todo(fields):
    cat = fields["status"].get("statusCategory") or {}
    if cat.get("key"):
        return cat["key"].lower() in TODO_CATEGORY_KEYS
    return (cat.get("name") or "").strip().lower() == "to do"


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--issues", nargs="*", default=None,
                   help="scoped check: only these keys must be out of To Do "
                        "(skips the sprint-membership rules)")
    p.add_argument("--json", action="store_true", help="machine-readable output")
    args = p.parse_args()

    try:
        jira = Jira()
    except (SystemExit, AtlassianGuardError) as exc:
        # SystemExit covers missing creds; AtlassianGuardError covers a
        # disallowed ATLASSIAN_URL (e.g. the -dev service site). Both are
        # configuration errors and must funnel to exit-2, per the docstring.
        print("CONFIG ERROR: %s" % exc, file=sys.stderr)
        return 2

    report = {"gate": "sprint9-no-todo", "checks": [], "violations": [], "passed": False}

    try:
        if args.issues:
            scope = list(args.issues)
        else:
            sprint = next((s for s in jira.sprints(RCP_SCRUM_BOARD)
                           if s["name"].strip().lower() == SPRINT_NAME.lower()), None)
            if not sprint:
                report["violations"].append(
                    "Sprint 9 does not exist on board %d — a missing sprint is a "
                    "vacuous pass, not a pass" % RCP_SCRUM_BOARD)
                return finish(report, args)
            report["sprint"] = {"id": sprint["id"], "state": sprint["state"]}
            if sprint["state"] not in ("active", "closed"):
                report["violations"].append(
                    "Sprint 9 is %r; expected active or closed" % sprint["state"])
            members = {i["key"] for i in jira.sprint_issues(sprint["id"])}
            report["member_count"] = len(members)
            for key, what in sorted(REQUIRED.items()):
                if key not in members:
                    report["violations"].append(
                        "%s is not in Sprint 9 (%s) — required items cannot be "
                        "dropped without a charter update" % (key, what))
            report["dropped"] = sorted(k for k in DROPPABLE if k not in members)
            scope = [k for k in COMMITTED if k in members]

        for key in sorted(scope):
            f = jira.issue(key, fields="summary,status")["fields"]
            todo = is_todo(f)
            report["checks"].append({
                "key": key, "status": f["status"]["name"],
                "category": (f["status"].get("statusCategory") or {}).get("name"),
                "todo": todo,
            })
            if todo:
                report["violations"].append(
                    "%s is in To Do (%s) — %s"
                    % (key, f["status"]["name"], COMMITTED.get(key, "scoped check")))
    except RuntimeError as exc:
        print("API ERROR: %s" % exc, file=sys.stderr)
        return 2

    return finish(report, args)


def finish(report, args):
    report["passed"] = not report["violations"]
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        for c in report["checks"]:
            print("%-9s %-14s %s" % (c["key"], c["status"], "TO DO" if c["todo"] else "ok"))
        for d in report.get("dropped", []):
            print("%-9s %-14s dropped from sprint (D6 timebox) — exempt"
                  % (d, "-"))
        if report["violations"]:
            print("\nHARD GATE FAILED — %d violation(s):" % len(report["violations"]))
            for v in report["violations"]:
                print("  - %s" % v)
        else:
            print("\nHARD GATE PASSED — no committed Sprint 9 item is in To Do.")
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
