#!/usr/bin/env python3
"""Sprint 10 HARD GATE — no committed Sprint 10 item may sit in To Do.

Sprint 10 successor of ``sprint9_hard_gate.py`` (same rules, Sprint 10
constants), plus ``--charter``: the day-1 form named by RCP-99. It runs
rules 1, 2 and 4 and requires the sprint to be ``active``; it skips rule 3,
because on day 1 every item is legitimately in To Do. ``--charter`` proves
the board is honest at charter time; the full gate is the close gate.

This is the gate the Sprint 10 close is judged by. It is read-only and
lives in its own file on purpose: nothing that can move an issue shares a module
with the check that reads it. Do not edit this file to make a run pass — that is
the reward-hacking failure mode the harness exists to prevent. If the gate is
wrong, change it in its own commit, with a reason, before the run that needs it.

The rule
--------
Exit 0 only when ALL of these hold:

1. **Sprint 10 exists** on the RCP scrum board and is ``active`` or ``closed``.
   Without this, "no sprint" would mean "no items" would mean "gate passes" —
   the vacuous pass the Sprint 9 charter names in R2.
2. **Every non-droppable committed item is a sprint member.** Otherwise the gate
   could be satisfied by emptying the sprint.
3. **No committed item that is in the sprint sits in the To Do status
   category.** Done, In Progress and In Review all pass — matching the sprint's
   definition of done: every item is delivered, in review, or consciously
   dropped.
4. **Every committed SI has an RCP acceptance row the BOARD ACTUALLY RENDERS.**
   Added 2026-09-01 (KAN-260) after this gate reported PASS for four days on a
   sprint the RCP board displayed as a single row.

Rule 4, and why it is not a member/rendered delta
-------------------------------------------------
Board 168's filter is ``project = RCP ORDER BY Rank ASC``. KAN is a separate,
team-managed project, so **a KAN key added to this sprint is a member that no
column can ever show.** ``/rest/agile/1.0/sprint/{id}/issue`` returns membership
and ignores the filter; ``/rest/agile/1.0/board/{b}/sprint/{id}/issue`` returns
what is rendered. Rules 2 and 3 read the first endpoint only, so they were blind
to a board with nothing on it.

The obvious repair — diff the two endpoints, fail on the delta — is **wrong, and
would be red on the one sprint that got this right.** Sprint 8 is 13 members and
6 rendered: its KAN execution rows are *supposed* to be members (rule 2 demands
it) and structurally cannot render, and its epic renders in the epic panel
rather than a column. A delta rule would also reward deleting KAN rows from the
sprint, which breaks rule 2.

So rule 4 asserts what Sprint 8 actually did: **one RCP ``S<N> acceptance:``
Story per SI, present in the board-scoped result.** The epic is never required
there. A D6-dropped SI is exempt, exactly as it is under rule 3.

Droppable items
---------------
Sprint 10 pre-authorises none. Adam's 2026-09-29 cuts (grill rows #4, #11, #12)
happened before the charter, so those items were never committed. Dropping a
committed item requires a charter update, not a gate edit.

What this gate does NOT prove
-----------------------------
Status alone is weak evidence. A Jira global rule still moves a ticket
``To Do -> In Progress`` when a branch is created for it, so an item can leave
To Do without any work happening. That is why each harness task carries its own
artifact check (PR state, CI rollup) and a named-evidence requirement on top of
this gate. Passing here means the board is honest, not that the sprint is done.

Usage
-----
    python3 scripts/harness/sprint10_hard_gate.py            # full (close) gate
    python3 scripts/harness/sprint10_hard_gate.py --charter  # day-1 gate
    python3 scripts/harness/sprint10_hard_gate.py --issues KAN-268
    python3 scripts/harness/sprint10_hard_gate.py --json

Exit codes: 0 pass · 1 gate failed · 2 configuration or API error.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _jira_client import Jira  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "pm"))
from _atlassian_guard import AtlassianGuardError  # noqa: E402

RCP_SCRUM_BOARD = 168
SPRINT_NAME = "Sprint 10"

# Committed items that must be in the sprint and, at close, out of To Do.
# Charter: specs/SPRINT_10_PLAN.md. Adam cut grill rows #4, #11 and #12 on
# 2026-09-29; they are not here and need no exemption.
REQUIRED = {
    "RCP-100": "epic — Sprint 10 delivery/acceptance",
    "KAN-268": "S1  — Flask Valkey IAM auth fix (non-droppable)",
    "KAN-292": "S2  — Datadog RUM behind consent, live >= 7 days before launch",
    "KAN-293": "S3  — mobile LCP residual on /r and /browse",
    "KAN-181": "S4  — KAN-181 INV-1..INV-9 production re-walk",
    "KAN-294": "S5  — header/footer nav parity SPA vs SSR",
    "KAN-295": "S6  — visible SPA breadcrumbs",
    "KAN-296": "S7  — numbered pagination on /browse and tag hubs",
    "KAN-297": "S8  — mobile 2-up card layout",
    "KAN-298": "S9  — filter/sort, /browse?sort&tag canonical to /browse",
    "KAN-277": "S10 — owned-property links + 3-5 articles",
    "KAN-299": "S11 — launch post, last, behind the four gates",
    # S12-S16: the five Sprint 8 retro carry-overs, ticketed into Sprint 10 by
    # Adam on 2026-09-29 (Sprint 9 retro action c).
    "KAN-300": "S12 — workflow secrets.* references gated against gh secret list",
    "KAN-301": "S13 — CLAUDE.md suppressed-comment (review body) sweep",
    "KAN-302": "S14 — delete the copied required-checks list from CLAUDE.md",
    "KAN-303": "S15 — pre-work branch preflight incl. Backend-pointer ancestry",
    "KAN-304": "S16 — CLAUDE.md platform-vs-code CI discriminator",
}

# Sprint items -> the execution rows that carry them.
SI_EXECUTION = {
    "S1": ["KAN-268"],
    "S2": ["KAN-292"],
    "S3": ["KAN-293"],
    "S4": ["KAN-181"],
    "S5": ["KAN-294"],
    "S6": ["KAN-295"],
    "S7": ["KAN-296"],
    "S8": ["KAN-297"],
    "S9": ["KAN-298"],
    "S10": ["KAN-277"],
    "S11": ["KAN-299"],
    "S12": ["KAN-300"],
    "S13": ["KAN-301"],
    "S14": ["KAN-302"],
    "S15": ["KAN-303"],
    "S16": ["KAN-304"],
}

# Sprint items -> the RCP acceptance Story the BOARD renders for them. ``None``
# means the row was never filed — a violation, not a skip (KAN-260).
ACCEPTANCE = {
    "S1": "RCP-98",
    "S2": "RCP-101",
    "S3": "RCP-102",
    "S4": "RCP-103",
    "S5": "RCP-104",
    "S6": "RCP-105",
    "S7": "RCP-106",
    "S8": "RCP-107",
    "S9": "RCP-108",
    "S10": "RCP-109",
    "S11": "RCP-110",
    "S12": "RCP-111",
    "S13": "RCP-112",
    "S14": "RCP-113",
    "S15": "RCP-114",
    "S16": "RCP-115",
}

# Sprint 10 pre-authorises no drops. S3's "evidence-only" flip changes how S3
# closes, not whether it is in the sprint. Dropping anything is a charter update.
DROPPABLE_SIS = set()
DROPPABLE = {}

COMMITTED = dict(REQUIRED, **DROPPABLE)
TODO_CATEGORY_KEYS = {"new", "undefined"}


def is_todo(fields):
    cat = fields["status"].get("statusCategory") or {}
    if cat.get("key"):
        return cat["key"].lower() in TODO_CATEGORY_KEYS
    return (cat.get("name") or "").strip().lower() == "to do"


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--issues", nargs="+", default=None,
                      help="scoped check: only these keys must be out of To Do "
                           "(skips the sprint-membership rules)")
    mode.add_argument("--charter", action="store_true",
                      help="day-1 gate: rules 1, 2, 4 with the sprint active; "
                           "skips rule 3 (To Do)")
    p.add_argument("--json", action="store_true", help="machine-readable output")
    args = p.parse_args()

    try:
        jira = Jira()
    except (SystemExit, AtlassianGuardError) as exc:
        # SystemExit covers missing creds; AtlassianGuardError covers a
        # disallowed ATLASSIAN_URL (e.g. the -dev service site). Both are
        # configuration errors and must funnel to exit-2, per the docstring.
        print("CONFIG ERROR: %s" % exc, file=sys.stderr)
        return 2

    gate = (
        "sprint10-charter" if args.charter
        else "sprint10-scoped-status" if args.issues is not None
        else "sprint10-no-todo"
    )
    report = {"gate": gate, "checks": [], "violations": [], "passed": False}
    status_descriptions = dict(COMMITTED)

    try:
        if args.issues:
            scope = list(args.issues)
        else:
            sprint = next((s for s in jira.sprints(RCP_SCRUM_BOARD)
                           if s["name"].strip().lower() == SPRINT_NAME.lower()), None)
            if not sprint:
                report["violations"].append(
                    "Sprint 10 does not exist on board %d — a missing sprint is a "
                    "vacuous pass, not a pass" % RCP_SCRUM_BOARD)
                return finish(report, args)
            report["sprint"] = {"id": sprint["id"], "state": sprint["state"]}
            allowed = ("active",) if args.charter else ("active", "closed")
            if sprint["state"] not in allowed:
                report["violations"].append(
                    "Sprint 10 is %r; expected %s" % (sprint["state"], " or ".join(allowed)))
            members = {i["key"] for i in jira.sprint_issues(sprint["id"])}
            report["member_count"] = len(members)
            for key, what in sorted(REQUIRED.items()):
                if key not in members:
                    report["violations"].append(
                        "%s is not in Sprint 10 (%s) — required items cannot be "
                        "dropped without a charter update" % (key, what))
            report["dropped"] = sorted(k for k in DROPPABLE if k not in members)

            # Rule 4 — board visibility. Read what the BOARD renders, not what the
            # sprint contains; the module docstring explains why this is not a
            # member/rendered delta.
            rendered = {i["key"] for i in
                        jira.board_sprint_issues(RCP_SCRUM_BOARD, sprint["id"])}
            report["board_rendered"] = sorted(rendered)
            report["acceptance"] = {}
            active_acceptance = {}
            for si in sorted(SI_EXECUTION):
                dropped = not any(k in members for k in SI_EXECUTION[si])
                row = ACCEPTANCE.get(si)
                if dropped and si in DROPPABLE_SIS:
                    if not row:
                        report["acceptance"][si] = "dropped — MISSING MAPPING"
                        report["violations"].append(
                            "%s is treated as dropped but has no acceptance-row "
                            "mapping, so the gate cannot prove the SI was removed "
                            "as a unit" % si)
                    elif row in members or row in rendered:
                        report["acceptance"][si] = "STRANDED — %s" % row
                        report["violations"].append(
                            "%s is treated as dropped because execution row(s) %s "
                            "left Sprint 10, but acceptance row %s remains in the "
                            "sprint/board — remove the SI as a unit"
                            % (si, "/".join(SI_EXECUTION[si]), row))
                    else:
                        report["acceptance"][si] = "dropped"
                    continue
                report["acceptance"][si] = row
                if not row:
                    report["violations"].append(
                        "%s has no RCP acceptance row — board %d filters "
                        "`project = RCP`, so its execution row(s) %s are sprint "
                        "members that no column renders"
                        % (si, RCP_SCRUM_BOARD, "/".join(SI_EXECUTION[si])))
                elif row not in rendered:
                    report["violations"].append(
                        "%s's acceptance row %s is not rendered by board %d for "
                        "this sprint — add it to the sprint, or the item is "
                        "invisible on the board" % (si, row, RCP_SCRUM_BOARD))
                else:
                    active_acceptance[row] = "%s — board-visible acceptance" % si

            # Acceptance rows are first-class committed sprint artifacts too;
            # rule 3 must reject one left in To Do just like its execution row.
            # Use setdefault so a row already described by COMMITTED keeps its
            # more specific charter/timebox context.
            for k, v in active_acceptance.items():
                status_descriptions.setdefault(k, v)
            scope = ({k for k in COMMITTED if k in members}
                     | {k for k in active_acceptance if k in members})

        if args.charter:
            scope = []  # rule 3 is the close gate; day 1 is all To Do by design
        for key in sorted(scope):
            f = jira.issue(key, fields="summary,status")["fields"]
            todo = is_todo(f)
            report["checks"].append({
                "key": key, "status": f["status"]["name"],
                "category": (f["status"].get("statusCategory") or {}).get("name"),
                "todo": todo,
            })
            if todo:
                report["violations"].append(
                    "%s is in To Do (%s) — %s"
                    % (key, f["status"]["name"],
                       status_descriptions.get(key, "scoped check")))
    except RuntimeError as exc:
        print("API ERROR: %s" % exc, file=sys.stderr)
        return 2

    return finish(report, args)


def finish(report, args):
    report["passed"] = not report["violations"]
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        for c in report["checks"]:
            print("%-9s %-14s %s" % (c["key"], c["status"], "TO DO" if c["todo"] else "ok"))
        for si, row in sorted(report.get("acceptance", {}).items()):
            print("%-9s %-14s %s" % (si, "acceptance",
                                     row if row else "MISSING — no RCP row"))
        for d in report.get("dropped", []):
            print("%-9s %-14s dropped from sprint (D6 timebox) — exempt"
                  % (d, "-"))
        if report["violations"]:
            print("\nHARD GATE FAILED — %d violation(s):" % len(report["violations"]))
            for v in report["violations"]:
                print("  - %s" % v)
        elif report["gate"] == "sprint10-scoped-status":
            print("\nSCOPED CHECK PASSED — every requested issue is out of To Do.")
        else:
            print("\nHARD GATE PASSED — every committed Sprint 10 item is %s AND has an "
                  "acceptance row the board renders." % (
                      "a member of the active sprint"
                      if report["gate"] == "sprint10-charter"
                      else "out of To Do"))
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
