#!/usr/bin/env python3
"""Sprint 9 HARD GATE — no committed Sprint 9 item may sit in To Do.

This is the gate the Sprint 9 agent-harness is judged by. It is read-only and
lives in its own file on purpose: nothing that can move an issue shares a module
with the check that reads it. Do not edit this file to make a run pass — that is
the reward-hacking failure mode the harness exists to prevent. If the gate is
wrong, change it in its own commit, with a reason, before the run that needs it.

The rule
--------
Exit 0 only when ALL of these hold:

1. **Sprint 9 exists** on the RCP scrum board and is ``active`` or ``closed``.
   Without this, "no sprint" would mean "no items" would mean "gate passes" —
   the vacuous pass the Sprint 9 charter names in R2.
2. **Every non-droppable committed item is a sprint member.** Otherwise the gate
   could be satisfied by emptying the sprint.
3. **No committed item that is in the sprint sits in the To Do status
   category.** Done, In Progress and In Review all pass — matching the sprint's
   definition of done: every item is delivered, in review, or consciously
   dropped.
4. **Every committed SI has an RCP acceptance row the BOARD ACTUALLY RENDERS.**
   Added 2026-09-01 (KAN-260) after this gate reported PASS for four days on a
   sprint the RCP board displayed as a single row.

Rule 4, and why it is not a member/rendered delta
-------------------------------------------------
Board 168's filter is ``project = RCP ORDER BY Rank ASC``. KAN is a separate,
team-managed project, so **a KAN key added to this sprint is a member that no
column can ever show.** ``/rest/agile/1.0/sprint/{id}/issue`` returns membership
and ignores the filter; ``/rest/agile/1.0/board/{b}/sprint/{id}/issue`` returns
what is rendered. Rules 2 and 3 read the first endpoint only, so they were blind
to a board with nothing on it.

The obvious repair — diff the two endpoints, fail on the delta — is **wrong, and
would be red on the one sprint that got this right.** Sprint 8 is 13 members and
6 rendered: its KAN execution rows are *supposed* to be members (rule 2 demands
it) and structurally cannot render, and its epic renders in the epic panel
rather than a column. A delta rule would also reward deleting KAN rows from the
sprint, which breaks rule 2.

So rule 4 asserts what Sprint 8 actually did: **one RCP ``S<N> acceptance:``
Story per SI, present in the board-scoped result.** The epic is never required
there. A D6-dropped SI is exempt, exactly as it is under rule 3.

Droppable items
---------------
Charter decision D6 pre-authorises dropping S5 (KAN-209), S7 (RCP-67) and S8
(KAN-176) against their half-day timeboxes. A dropped item is one *removed from
the sprint* — that is the board-visible act of dropping, and it exempts the item
from rule 3. Every other item must be present and out of To Do; dropping one
requires a charter update, not a gate edit.

What this gate does NOT prove
-----------------------------
Status alone is weak evidence. A Jira global rule still moves a ticket
``To Do -> In Progress`` when a branch is created for it, so an item can leave
To Do without any work happening. That is why each harness task carries its own
artifact check (PR state, CI rollup) and a named-evidence requirement on top of
this gate. Passing here means the board is honest, not that the sprint is done.

Usage
-----
    python3 scripts/harness/sprint9_hard_gate.py            # full gate
    python3 scripts/harness/sprint9_hard_gate.py --issues KAN-151
    python3 scripts/harness/sprint9_hard_gate.py --json

Exit codes: 0 pass · 1 gate failed · 2 configuration or API error.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _jira_client import Jira  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "pm"))
from _atlassian_guard import AtlassianGuardError  # noqa: E402

RCP_SCRUM_BOARD = 168
SPRINT_NAME = "Sprint 9"

# Committed items that must be in the sprint and out of To Do.
REQUIRED = {
    "RCP-88": "epic — Sprint 9 delivery/acceptance",
    "KAN-255": "S1a — image metadata never re-syncs after nav-away",
    "KAN-256": "S1a — generator does not reset on route entry",
    "KAN-257": "S1b — recipe-detail bounces to /kitchen; replaceUrl kills Back",
    "KAN-151": "S2  — Valkey response cache restore (ANCHOR)",
    "KAN-249": "S3  — split cloudbuild.staging.yaml out of cloudbuild.yaml",
    "KAN-250": "S3  — staging deploy moves to a GCP-side Cloud Build trigger",
    "KAN-258": "S4  — model-selection tail + v0.4.13 release cut",
    "KAN-195": "S6  — regenerated image blocked 24h by stale Cache-Control",
}

# Sprint items -> the execution rows that carry them. An SI whose execution rows
# are all absent from the sprint has been dropped (see DROPPABLE_SIS).
SI_EXECUTION = {
    "S1a": ["KAN-255", "KAN-256"],
    "S1b": ["KAN-257"],
    "S2": ["KAN-151"],
    "S3": ["KAN-249", "KAN-250"],
    "S4": ["KAN-258"],
    "S5": ["KAN-209"],
    "S6": ["KAN-195"],
    "S7": ["RCP-67"],
    "S8": ["KAN-176"],
}

# Sprint items -> the RCP acceptance Story the BOARD renders for them, mirroring
# Sprint 8's RCP-81..RCP-86. ``None`` means the row was never filed — a violation,
# not a skip: an SI with no board-visible row is invisible to anyone reading the
# sprint, which is the entire defect KAN-260 exists to correct.
#
# S7 is RCP-67 itself: already an RCP Story, already rendered, so it needs no
# separate acceptance row.
ACCEPTANCE = {
    "S1a": "RCP-89",
    "S1b": "RCP-90",
    "S2": "RCP-92",
    "S3": "RCP-93",
    "S4": "RCP-94",
    "S5": "RCP-95",
    "S6": "RCP-96",
    "S7": "RCP-67",
    "S8": "RCP-91",
}

# SIs whose D6 half-day timebox pre-authorises a drop.
DROPPABLE_SIS = {"S5", "S7", "S8"}

# D6 pre-authorised drops. Absent from the sprint == dropped == exempt.
DROPPABLE = {
    "KAN-209": "S5  — RESP2 pin revisit (half-day timebox)",
    "RCP-67": "S7  — route/request classification contract (half-day timebox)",
    "KAN-176": "S8  — flask-backend second guard (half-day timebox)",
}

COMMITTED = dict(REQUIRED, **DROPPABLE)
TODO_CATEGORY_KEYS = {"new", "undefined"}


def is_todo(fields):
    cat = fields["status"].get("statusCategory") or {}
    if cat.get("key"):
        return cat["key"].lower() in TODO_CATEGORY_KEYS
    return (cat.get("name") or "").strip().lower() == "to do"


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--issues", nargs="*", default=None,
                   help="scoped check: only these keys must be out of To Do "
                        "(skips the sprint-membership rules)")
    p.add_argument("--json", action="store_true", help="machine-readable output")
    args = p.parse_args()

    try:
        jira = Jira()
    except (SystemExit, AtlassianGuardError) as exc:
        # SystemExit covers missing creds; AtlassianGuardError covers a
        # disallowed ATLASSIAN_URL (e.g. the -dev service site). Both are
        # configuration errors and must funnel to exit-2, per the docstring.
        print("CONFIG ERROR: %s" % exc, file=sys.stderr)
        return 2

    report = {"gate": "sprint9-no-todo", "checks": [], "violations": [], "passed": False}
    status_descriptions = dict(COMMITTED)

    try:
        if args.issues:
            scope = list(args.issues)
        else:
            sprint = next((s for s in jira.sprints(RCP_SCRUM_BOARD)
                           if s["name"].strip().lower() == SPRINT_NAME.lower()), None)
            if not sprint:
                report["violations"].append(
                    "Sprint 9 does not exist on board %d — a missing sprint is a "
                    "vacuous pass, not a pass" % RCP_SCRUM_BOARD)
                return finish(report, args)
            report["sprint"] = {"id": sprint["id"], "state": sprint["state"]}
            if sprint["state"] not in ("active", "closed"):
                report["violations"].append(
                    "Sprint 9 is %r; expected active or closed" % sprint["state"])
            members = {i["key"] for i in jira.sprint_issues(sprint["id"])}
            report["member_count"] = len(members)
            for key, what in sorted(REQUIRED.items()):
                if key not in members:
                    report["violations"].append(
                        "%s is not in Sprint 9 (%s) — required items cannot be "
                        "dropped without a charter update" % (key, what))
            report["dropped"] = sorted(k for k in DROPPABLE if k not in members)

            # Rule 4 — board visibility. Read what the BOARD renders, not what the
            # sprint contains; the module docstring explains why this is not a
            # member/rendered delta.
            rendered = {i["key"] for i in
                        jira.board_sprint_issues(RCP_SCRUM_BOARD, sprint["id"])}
            report["board_rendered"] = sorted(rendered)
            report["acceptance"] = {}
            active_acceptance = {}
            for si in sorted(SI_EXECUTION):
                dropped = not any(k in members for k in SI_EXECUTION[si])
                row = ACCEPTANCE.get(si)
                if dropped and si in DROPPABLE_SIS:
                    if not row:
                        report["acceptance"][si] = "dropped — MISSING MAPPING"
                        report["violations"].append(
                            "%s is treated as dropped but has no acceptance-row "
                            "mapping, so the gate cannot prove the SI was removed "
                            "as a unit" % si)
                    elif row in members or row in rendered:
                        report["acceptance"][si] = "STRANDED — %s" % row
                        report["violations"].append(
                            "%s is treated as dropped because execution row(s) %s "
                            "left Sprint 9, but acceptance row %s remains in the "
                            "sprint/board — remove the SI as a unit"
                            % (si, "/".join(SI_EXECUTION[si]), row))
                    else:
                        report["acceptance"][si] = "dropped"
                    continue
                report["acceptance"][si] = row
                if not row:
                    report["violations"].append(
                        "%s has no RCP acceptance row — board %d filters "
                        "`project = RCP`, so its execution row(s) %s are sprint "
                        "members that no column renders"
                        % (si, RCP_SCRUM_BOARD, "/".join(SI_EXECUTION[si])))
                elif row not in rendered:
                    report["violations"].append(
                        "%s's acceptance row %s is not rendered by board %d for "
                        "this sprint — add it to the sprint, or the item is "
                        "invisible on the board" % (si, row, RCP_SCRUM_BOARD))
                else:
                    active_acceptance[row] = "%s — board-visible acceptance" % si

            # Acceptance rows are first-class committed sprint artifacts too;
            # rule 3 must reject one left in To Do just like its execution row.
            status_descriptions.update(active_acceptance)
            scope = ({k for k in COMMITTED if k in members}
                     | {k for k in active_acceptance if k in members})

        for key in sorted(scope):
            f = jira.issue(key, fields="summary,status")["fields"]
            todo = is_todo(f)
            report["checks"].append({
                "key": key, "status": f["status"]["name"],
                "category": (f["status"].get("statusCategory") or {}).get("name"),
                "todo": todo,
            })
            if todo:
                report["violations"].append(
                    "%s is in To Do (%s) — %s"
                    % (key, f["status"]["name"],
                       status_descriptions.get(key, "scoped check")))
    except RuntimeError as exc:
        print("API ERROR: %s" % exc, file=sys.stderr)
        return 2

    return finish(report, args)


def finish(report, args):
    report["passed"] = not report["violations"]
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        for c in report["checks"]:
            print("%-9s %-14s %s" % (c["key"], c["status"], "TO DO" if c["todo"] else "ok"))
        for si, row in sorted(report.get("acceptance", {}).items()):
            print("%-9s %-14s %s" % (si, "acceptance",
                                     row if row else "MISSING — no RCP row"))
        for d in report.get("dropped", []):
            print("%-9s %-14s dropped from sprint (D6 timebox) — exempt"
                  % (d, "-"))
        if report["violations"]:
            print("\nHARD GATE FAILED — %d violation(s):" % len(report["violations"]))
            for v in report["violations"]:
                print("  - %s" % v)
        else:
            print("\nHARD GATE PASSED — every committed Sprint 9 item is out of To "
                  "Do AND has an acceptance row the board renders.")
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
